version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cars_db
    ports:
      - "5432:5432" # Expose database port for local access (optional)
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist database data

  # Node.js Backend Service
  backend:
    build:
      context: ./backend # Build from the backend directory
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cars_db
      POSTGRES_HOST: db # Use the service name of the database container
    depends_on:
      - db # Ensure database starts before the backend

  # Nginx Frontend Server (to serve index.html and proxy API requests)
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "81:80" # Serve on port 80
    volumes:
      - ./app:/usr/share/nginx/html # Mount frontend files
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount Nginx configuration
    depends_on:
      - backend # Ensure backend starts before Nginx

volumes:
  pgdata:
